export const QUERY_KEYS = {
  userDetails: 'user-details',
  cars: 'cars',
  clients: 'clients',
  salespeople: 'salespeople',
  sales: 'sales',
  reports: 'reports',
  ownerDashboard: 'owner-dashboard',
  salespersonDashboard: 'salesperson-dashboard',
  car: (id: string) => `car-${id}`,
  salesperson: (id: string) => `salesperson-${id}`,
  salespersonCars: (id: string) => `salesperson-${id}-cars`,
  login: 'login',
  logout: 'logout',
} as const;
